on:
  push:
    branches:
      - main

name: generate-manifests

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    env:
      CONTENT_PATH: "content/document.Rmd"
      R_VERSION: 4.0.5
      BUNDLE_PATH: "bundles-4.0.5/"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Install R
      run: bash utils/install-r.sh
      env: 
        R_VERSION: ${{ env.R_VERSION }}

    - name: Install rsconnect
      run: |
        options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/focal/latest"))
        install.packages('rsconnect')
      shell: Rscript {0}

    - name: Copy content to bundle
      run: |
        mkdir ${{ env.BUNDLE_PATH }}
        cp ${{ env.CONTENT_PATH }} ${{ env.BUNDLE_PATH }}

    - name: Generate manifest.json
      run: |
        rsconnect::writeManifest(appDir = "${{ env.BUNDLE_PATH }}")
      shell: Rscript {0}

    - name: Push the new manifest to the repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ${{ env.BUNDLE_PATH }}
        git commit -m "GH ACTION - manifest file generated"
        git push -q