on:
  push:
    branches:
      - main

name: generate-manifests

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    env:
      CONTENT_PATH: "content/document.Rmd"
      R_VERSION: 4.0.5
      BUNDLE_PATH: "bundles-4.0.5/"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Install R
      run: bash utils/install-r.sh
      env: 
        R_VERSION: ${{ env.R_VERSION }}

    - name: Generate manifest.json
      run: sudo Rscript utils/write-manifest.R
      env: 
        R_VERSION: ${{ env.R_VERSION }}
        CONTENT_PATH: ${{ env.CONTENT_PATH}}

    - name: Push the new manifest to the repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ${{ env.BUNDLE_PATH }}
        git commit -m "GH ACTION - manifest file generated"
        git push -q