on:
  push:
    branches:
      - main

name: generate-manifests

jobs:
  generate-manifests:
    runs-on: ubuntu-latest
    env:
      CONTENT_PATH: "content/document.Rmd"
      R_VERSION: 4.0.5
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Install R
        run: bash utils/install-r.sh
        env: 
          R_VERSION: ${{ env.R_VERSION }}

    - name: Generate manifest.json
        run: Rscript utils/write-manifest.R